# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_morph_tree_alpha_aux', [dirname(__file__)])
        except ImportError:
            import _morph_tree_alpha_aux
            return _morph_tree_alpha_aux
        if fp is not None:
            try:
                _mod = imp.load_module('_morph_tree_alpha_aux', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _morph_tree_alpha_aux = swig_import_helper()
    del swig_import_helper
else:
    import _morph_tree_alpha_aux
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def get_descendants_aux_c(*args, **kwargs):
  """get_descendants_aux_c(int node, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.get_descendants_aux_c(*args, **kwargs)

def get_ancestors_aux_c(*args, **kwargs):
  """get_ancestors_aux_c(int node, int DIM1)"""
  return _morph_tree_alpha_aux.get_ancestors_aux_c(*args, **kwargs)

def get_children_aux_c(*args, **kwargs):
  """get_children_aux_c(int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.get_children_aux_c(*args, **kwargs)

def get_sub_branches_aux_c(*args, **kwargs):
  """get_sub_branches_aux_c(int DIM1, int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.get_sub_branches_aux_c(*args, **kwargs)

def contract_dr_aux_c(*args, **kwargs):
  """contract_dr_aux_c(int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.contract_dr_aux_c(*args, **kwargs)

def update_nchild_aux_c(*args, **kwargs):
  """update_nchild_aux_c(int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.update_nchild_aux_c(*args, **kwargs)

def prune_aux_c(*args, **kwargs):
  """prune_aux_c(int DIM1, int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.prune_aux_c(*args, **kwargs)

def get_image_aux_2d_c(*args, **kwargs):
  """get_image_aux_2d_c(int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.get_image_aux_2d_c(*args, **kwargs)

def get_image_aux_3d_c(*args, **kwargs):
  """get_image_aux_3d_c(int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.get_image_aux_3d_c(*args, **kwargs)

def rec_connected_component_2d_c(*args, **kwargs):
  """rec_connected_component_2d_c(int node, int seed, int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.rec_connected_component_2d_c(*args, **kwargs)

def rec_connected_component_3d_c(*args, **kwargs):
  """rec_connected_component_3d_c(int node, int seed, int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.rec_connected_component_3d_c(*args, **kwargs)

def lut_node_index_2d_c(*args, **kwargs):
  """lut_node_index_2d_c(int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.lut_node_index_2d_c(*args, **kwargs)

def lut_node_index_3d_c(*args, **kwargs):
  """lut_node_index_3d_c(int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.lut_node_index_3d_c(*args, **kwargs)

def remove_node_array_lines_c(*args, **kwargs):
  """remove_node_array_lines_c(int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.remove_node_array_lines_c(*args, **kwargs)

def get_bif_ancestor_aux_c(*args, **kwargs):
  """get_bif_ancestor_aux_c(int node, int DIM1, int DIM1) -> int"""
  return _morph_tree_alpha_aux.get_bif_ancestor_aux_c(*args, **kwargs)

def compute_hist_aux_c(*args, **kwargs):
  """compute_hist_aux_c(int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.compute_hist_aux_c(*args, **kwargs)

def compute_node_gray_avg_aux_c(*args, **kwargs):
  """compute_node_gray_avg_aux_c(int DIM1, int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.compute_node_gray_avg_aux_c(*args, **kwargs)

def compute_node_gray_var_aux_c(*args, **kwargs):
  """compute_node_gray_var_aux_c(int DIM1, int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.compute_node_gray_var_aux_c(*args, **kwargs)

def compute_eccentricity_aux_c(*args, **kwargs):
  """compute_eccentricity_aux_c(int DIM1, int DIM1, int DIM1, int DIM1, int DIM1)"""
  return _morph_tree_alpha_aux.compute_eccentricity_aux_c(*args, **kwargs)
# This file is compatible with both classic and new-style classes.


